### ISSUE TITLE
Not able to change updateStrategy for masters deployment to recreate

### ISSUE THREAD

**Issue by tarioch** [puppetlabs/puppetserver-helm-chart#111]
## Describe the Bug
At the moment there is an updateStrategy config but I can't change it to recreate as there are additional rollingUpdate settings which are forbidden with recreate.

## Expected Behavior
I would expect to be able to specify something like

```yaml
puppetserver:
  masters:
    updateStrategy:
      type: Recreate
```

in my values file and it to work.

But because of 

```yaml
      rollingUpdate:
        maxSurge: 20%
        maxUnavailable: 0%
```

in the default values file, it will fail.

My suggestion would be to remove the maxSurge/maxUnavailable settings from the default values file. Or alternatively only add them if the updateStrategy is rollingUpdate.

**Comment by davidphay** [comment]
Hello,

you can use the follow syntax, it should works:
```yaml
puppetserver:
  masters:
    updateStrategy:
      type: Recreate
      rollingUpdate:
```
