### ISSUE TITLE
Helm chart doesn't install

### ISSUE THREAD

**Issue by akiryushin** [puppetlabs/puppetserver-helm-chart#148]
## Describe the Bug
If there are multiple annotation of storage in values, helm won't install chart. Kubernetes expects valid yaml PVC manifest of puppetdb but puppetdb-pvc is unvalid due to annotations.

## Expected Behavior
PVC of puppetdb must be valid.

## Steps to Reproduce
1. helm repo add puppet https://puppetlabs.github.io/puppetserver-helm-chart
2. Create values.yaml
```
storage:
  annotations:
    my-annotation-1: test
    my-annotation-2: test
```
3. helm install --namespace puppetserver --name puppetserver puppet/puppetserver -f values.yaml

## Environment
 - Kuberenets v1.19
 - Helm v3.10.0

## Additional Context
Need to fix puppetdb-pvc.yaml. In annotation block add `nindent`
