### ISSUE TITLE
Custom ENC

### ISSUE THREAD

**Issue by antwacky** [puppetlabs/puppetserver-helm-chart#169]
I'm trying to add a custom ENC to puppet, is there a recommended way to do this using this helm chart?

**Comment by davidphay** [comment]
Hi, I'm not aware how ENC work so I can't really help, if someone else know feel free to open a PR if needed !

**Comment by tom-ph** [comment]
Hi, I was thinking how this could be done and maybe I have a solution. I started by seeing how the autosign is managed on the puppetlabs/puppetagent docker image, that is by running the *60-setup-autosign.sh* script in the *docker.entrypoint.d* folder. This is the code:
```
#!/bin/bash

# Configure puppet to use a certificate autosign script (if it exists)
# AUTOSIGN=true|false|path_to_autosign.conf
if test -n "${AUTOSIGN}" ; then
  puppet config set autosign "$AUTOSIGN" --section master
fi
```

So in order to setup the ENC you should create a similar script like:
```
#!/bin/bash

# Configure puppet to use a custom ENC script (if it exists)
if test -n "${PUPPETSERVER_ENC_PATH}" ; then
  puppet config set node_terminus "exec" --section master
  puppet config set external_nodes "$PUPPETSERVER_ENC_PATH" --section master
fi
```
You will then need to do the following:
1. add this script to the **puppetserver.customentrypoints** key in the *values.yaml* file
2. add the actual ENC script to the puppet agent. I have opened an issue to allow adding custom configmaps to the puppetserver for a different but similar reason, you can find my current workaround there:   https://github.com/puppetlabs/puppetserver-helm-chart/issues/167
3. add the PUPPETSERVER_ENC_PATH to the **puppetserver.extraEnv** key in the *values.yaml* file (of course the name is arbitrary, it just needs to be the same as defined in the script) pointing to the ENC script path.

I didn't have the chance to test it, but I think it should work.

Hope this helps, and if someone has a cleaner solution please share!

**Comment by robkooper** [comment]
I ended up creating a flask app that can be used as a ENC and runs next to the puppet server in kubernetes. Hosts can be added, modified and removed using REST api calls (i.e. using curl). I ended up adding a new customentrypoints that would add a 3 line shell script to the docker image. The script will call the second container that runs the enc.

You can find the repository at: https://github.com/ncsa/puppet-enc

**Comment by robkooper** [comment]
I'll try and create a PR to help with the process.

**Comment by antwacky** [comment]
The below worked. The handy things to add to the chart would be the ability to add custom volumes/volumemounts as suggested by @tom-ph.

I'll leave the issue open in case anyone gets round to updating the chart, however using kustomize to patch is just as good (so feel free to close).

Add ConfigMap volume with ENC script (and requirements.txt in my case as it's python):

```
# kustomize patches
      - op: add
        path: /spec/template/spec/volumes/-
        value:
          name: enc
          configMap:
            name: enc-volume
            defaultMode: 0755
      - op: add
        path: /spec/template/spec/containers/0/volumeMounts/-
        value:
          mountPath: /usr/local/bin/enc
          name: enc
          subPath: enc
      - op: add
        path: /spec/template/spec/containers/0/volumeMounts/-
        value:
          mountPath: /tmp/requirements.txt
          name: enc
          subPath: requirements.txt
```

Add custom entry points to configure enc:

```
  # ENC configuration
  customentrypoints:
    enabled: true
    configmaps:
      configure_enc.sh: |-
        #!/bin/bash
        
        # Install ENC prereqs
        apt update
        apt install -y jq bash curl python3 python3-pip
        pip3 install -r /tmp/requirements.txt

        # Configure puppet to use a custom ENC script (if it exists)
        if test -n "${PUPPETSERVER_ENC_PATH}" ; then
          puppet config set node_terminus "exec" --section master
          puppet config set external_nodes "$PUPPETSERVER_ENC_PATH" --section master
        fi
  extraEnv:
    PUPPETSERVER_ENC_PATH: /usr/local/bin/enc
```
