### ISSUE TITLE
Allow to specify a node port

### ISSUE THREAD

**Issue by qdii** [puppetlabs/puppetserver-helm-chart#181]
## Use Case
On bare metal installations of Kubernetes, it is often useful to set up services of type `NodePort` to make a node's port available for the service.

Currently, the helm chart allow to change the `type` of the service, but note to specify a `nodePort`, which results in this port to be randomly allocated. Worse, the port isn't stable through upgrades of the charts.

## Describe the Solution You Would Like
An additional `nodePort` field should be available in the chart.

## Describe Alternatives You've Considered
TLS passthrough via Ingress may be a workaround.

## Additional Context
None

**Comment by ldaneliukas** [comment]
Hey!

Does the following not meet your needs:
```
puppetserver:
  masters:
    service:
      type: NodePort
      ports:
        puppetserver:
          port: 8140
          nodePort: 18140
          protocol: TCP
```

Results in:
```
NAME                         TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)
puppetserver-puppet          NodePort    10.252.178.61    <none>        8140:18140/TCP
```
