### ISSUE TITLE
Wrong parameter name in README to disable autosign

### ISSUE THREAD

**Issue by hrekov** [puppetlabs/puppetserver-helm-chart#79]
In section of the README.md `Auto-Signing Certificate Requests` instead of `.Values.puppetserver.extraEnv` should be `.Values.puppetserver.masters.extraEnv` because first variant not working

**Comment by hrekov** [comment]
Also it would be great to provide an example like this :
```
puppetserver:
    masters:
        extraEnv:
            AUTOSIGN: false
```
